### ISSUE TITLE
Implementação

### ISSUE THREAD

**Issue by RogerioTonini** [MikelSFraga/ApiFunction#5]
Oi Mikel, não conheço muito bem como trabalhar com classes. Estou levando uma surra para tentar utilizar sua ferramenta.
Utilizo o Office2016  64bits, versão 1805, e quando tento executar começa a dar erro logo na primeira linha VERSION 1.0 CLASS  até a linha: >>>>>>> develop.

Comentei todas e coloquei pra rodar, aparentemente esta funcionando (testei o botão de fechar o form). As demais vou ler mais e testar.

Se puder ajudar agradeço, já li muita coisa e não compreendi. Acho que com esta ferramenta, consigo visualizar melhor o que a ferramenta tem a oferecer de recursos.

Meu e-mail: rogerio.tonini@gmail.com, zap 11 985048872.

Muitíssimo obrigado.

**Comment by MikelSFraga** [comment]
Rogério, boa tarde.

Primeiro, quero agradecer pelo feedback.

Algumas pessoas mencionaram sobre um erro parecido. Tem duas situações que detectei como resultado:
- As pessoas tem realizado a importação do arquivo, mas o mesmo fica como Módulo comum. Esse erro não sei pq ocorre, mas vou iniciar alguns testes, para poder detectar uma possível causa;
- Outro problema é a cópia do código direto do GitHub, que esta sendo colado no Módulo de Classe do Excel. Nesse caso, as primeiras 11 linhas, não podem estar disponíveis no código, pois são sub-scripts da estrutura do Módulo de Classe, que não aparecem no script do VBE. Essa linha develop tb não existe e pode ser apagada.

De qualquer forma, vou dar uma analisada no código e retorno possíveis soluções.

No mais, muito obrigado pelo feedback.

**Comment by MikelSFraga** [comment]
Rogério, bom dia.

Conforme feedback de alguns erros detectados no processo de importação da classe, para uma nova Workbook no Excel, iniciei uma pesquisa e detectei um erro de configuração do Git.

Agora o arquivo que esta disponível no GitHub já esta funcionando nos testes que realizei.

Fica aqui meu agradecimento a todos que reportaram, mas reforço a continuidade dos testes e, na detecção de novos erros, darem novos feedback´s.

Obrigado a todos.

**Comment by RogerioTonini** [comment]
Valeu obrigado.
