### ISSUE TITLE
ApiFunction Classe

### ISSUE THREAD

**Issue by Andreluoliveira** [MikelSFraga/ApiFunction#6]
Olá Mikel, tudo bem?
Vi seu vídeo sobre a ApiFunction, que por sinal achei muito interessante.
Fiz o download do arquivo zipado e descompactei-o. Entretanto quando importo para dentro do vba ele vai como um módulo comum e não como um módulo de classe e causa alguns problemas. O que poderia estar dando errado neste processo?

grato,
André Oliveira.

**Comment by MikelSFraga** [comment]
Andre, boa tarde meu amigo. 

Já vi algumas pessoas reclamando desse problema, porém ainda não ocorreu comigo esse tipo de erro, mesmo em outras máquinas.

Vou pesquisar sobre esse problema e reporto aqui para vocês, mas acredito que possa ser alguma configuração específica. Tenho alguns palpites, mas preciso fazer alguns testes antes.

Assim que tiver um retorno, posto aqui. Abraços e obrigado pelo feedback.

**Comment by MikelSFraga** [comment]
André, bom dia.

Conforme feedback de alguns erros detectados no processo de importação da classe, para uma nova Workbook no Excel, iniciei uma pesquisa e detectei um erro de configuração do Git.

Agora o arquivo que esta disponível no GitHub já esta funcionando nos testes que realizei.

Fica aqui meu agradecimento a todos que reportaram, mas reforço a continuidade dos testes e, na detecção de novos erros, darem novos feedback´s.

Obrigado a todos.

**Comment by Andreluoliveira** [comment]
Valeu Mikel. Obrigado por contribuir com a gente!
